server {
    listen 80;                        # nginx listens on port 80

    # All normal requests → serve React build files
    location / {
        root /usr/share/nginx/html;   # where React build files are copied to
        index index.html;
        try_files $uri $uri/ /index.html;  # React Router fix — always fallback to index.html
    }

    # Requests starting with /api/ → forward to backend
    location /api/ {
        proxy_pass http://127.0.0.1:5000/;   # backend = service name in docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
